# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-25 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20180625_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='wife',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.Author'),
        ),
    ]
