# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='uemail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='uname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='number',
            new_name='uphone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='upwd',
        ),
    ]
