# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-24 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20180624_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=100)),
                ('uphone', models.CharField(max_length=11)),
                ('uemail', models.EmailField(max_length=254, null=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
